### ISSUE TITLE
Typo ;)

### ISSUE THREAD

**Issue by kg-currenxie** [Jcambass/sane_patch#1]
=> `Hello Folk`

**Comment by cbortz** [comment]
Also here: https://github.com/Jcambass/sane_patch/blob/1a44c9c670d62c46e3a8c6fc6fd0a66e25c2edbc/sane_patch.gemspec#L13

`sillently` should be `silently`

**Comment by Jcambass** [comment]
@kg-currenxie and @cbortz  Thx for being observant 👏🏻.
