### ISSUE TITLE
1.0 release?

### ISSUE THREAD

**Issue by jrochkind** [Jcambass/sane_patch#4]
What do you think? Makes me feel better when I can use semver requirements in my Gemfile, like "~> 1.0", but pre-1.0 is pre-semver so I don't really know when backwards incompats are expected or what requirements to put in my Gemfile. 

This is a useful gem to me.

**Comment by Jcambass** [comment]
You make a fair point. Let's go for a 1.0 release.

**Comment by Jcambass** [comment]
Closed by https://github.com/Jcambass/sane_patch/commit/e460968c07491ac97bc1f5a85a7c3788b706a391.
